travis:
  secure:
    BINSTAR_TOKEN: EJPPBo57BBYGrkpm/FikIYCxLJkMuz5qJEqJ7yMK3F6h33WtoBzmTKAZu9MjYOP4orYsHkdnqdPF/1Kd99IFJPu1ZZ5OAFFKXRbMWohdrz6OQMLWkC6GC+ef7sEvkgVkHZ1zZjVXs/ELMTCWVRfMfU8oM8PYxjTksFqaEU2YEScvU2g30fqK61d4HKVmoqt/Sj2hAgNYnjT8gfJqCO/LlkRHu/7k2qeBhlYaTAKoUGAnNxXfzFHD3xYQ3QY/Y0+ErW2/KVxywFsItzBj0sSSrNJXR+2kpewkC5pauU2ukOFZqvLxdZ95TqvG3caTCiRe2D2h6mQB3SrYqf9vVhoZDZasceW7pr+WxRGVX1rRX4LdwXDjRCfMa03iVyXlhvegkgBlSdnC5Cg4wACrjiZxyQ7fMMzlcNDqOATVl6IS7ensKqgU0ij/jO7Jg4s4LFwtnRCW66vb/8SEqT8+jIoPk3GRkqaAAZmSLdbKO3UCO+tWBWnNFWQvYogvOdLie9Y/NCvDyVW6phdUjGLe3aOuotEMhQmcYPK3PHwJvmrbeGAdj3OuJR/KxYv5s22Ybwd1hWEC8olbkUKVBVAheZ6F4aWdEyp3fsHHhYhNybpuRHUIhvt1uySHami7RsuMAMycZxKmGp/4jfk5VAzjneMTYdTsntRfiYB8/eOFiYWHbLM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
