travis:
  secure:
    BINSTAR_TOKEN: gD9GeTMxizxR/DDO7lK6KEiRkRXpjxkjpc7NCPNdxsqVJ0eu5lHzejtkunt6AYprYHgwBNNSbgEYJiL2X2DJilFI1J1djJJu2NK1+ISZTQdR4nUqvPAfUY0X7mCQpw24Q/9Pl1RCHy3bjwXSRFu+/MFEhMwYM4YCTzC56z7xZu7xYhGS7PBIgjbbMjCTPghrAsa6tSmL0VFlz/UO8fyXACAOp2XtsjesERZ1AMytZFQBZndKg1FMNyuT4b6NGxRsMtSnfnrA2kE6FaVedEnAKDmXeGKzmgqFh1BkcUUMAdGLtwDXSXEZtiK99Vb/8LVpxMtvdoHZlOa5FNO8v+QqMWhyn0qUn6l9uHemwUJuGXg5MQRyRg32xl4oRsQumMcny1mCudItG4QKKGUAaek1r5D2mkzYH0bo3b5JUGzhFOrqGZ5MY9cO+AB7GH0ZDoNlMlQkw/VT13WiGbPeqKN7pxrwLOjALBUzGewAebUkbBT/DNa4mySb4zWIcHRCBVZsSLsV73nAPfxFBUbYOwKywxUcZrNt7DqpSPIu+Dx1uoLEQA6Y9QSTQW3XlsX66VWeXGLj88koWyEoVPnSMhJhy1hT4amvcUhtQ4QWkwbupIDDdDgTns/im2B9ZiiN7x1pGe0AiQRyg5FDogD2kKBP5dOsHNHcURIznXymwI+UIxQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
