travis:
  secure:
    BINSTAR_TOKEN: RAgsEMWoTSOVdVrut49/GTrRmMVpoiTHpgqUyAlmSROXls5/w2MeFA9J0fiHA9wNbuZYJExCoL3gsjXnvZqOoeOSQkUc4tqK4CoN4+sodmnS7OqeducCe7iY2HKWshPAYRWEncET+R8B0SsObwFuKCJA69X788yxzk32GiUk+lN6b3AtGpssNko831mAUW/V/HMAC2KyclLAqNX7jkXtfLv72P7v5JydeXSsqj+Dpsy7vdiGX/aIz+kNKWiCxVFKoK7JTxKveTGxpgibuM9dv7FOX0Td7GHHeQmuCVVGCch4VK0pU+wJpo/kDNjo78LtjVC+RJKCMf8bCTruKzuopamgmlqm1mV96A6Wyv0bUcJXeHwkCVikK6zPrNLrb/eEG/3iDRPyUy5hyE9pF4cxnfXnq5+O+BBjzdB6p0ymlcRLBTP3+C52CY20tYKPrfa9N31zT7ODNzXMbUjS0SBBTVvqyV/MygUwMRlF1XYbG4zDhs80yiHcc2H3KFZnhL03+9/qkMWxNrQXEAf4hy2jEk/W9UH4DvrGZNVkvb014lfvTOm4+ieZPpiTFbIqUd3i4LeKqJJCeckoI6GRLoJAC49mRbA8Psz78ovAAVRgzHPnlPJFQsh8JFvufIWLXj1f6k7wqSqd2fGMVi2AkMgJ8fz9Y4IF0UcjLi58/B6uw4k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
